<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="main.UserExistsExceptionTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2025-01-10T18:00:24" hostname="DESKTOP-URGQT26" time="0.038">
  <properties/>
  <testcase name="constructor_withMessageAndCause_correctMessageUsed()" classname="main.UserExistsExceptionTest" time="0.028"/>
  <testcase name="constructor_withMessage_correctMessageUsed()" classname="main.UserExistsExceptionTest" time="0.002"/>
  <testcase name="constructor_withCause_correctMessageUsed()" classname="main.UserExistsExceptionTest" time="0.001"/>
  <testcase name="userExistsException_isCheckedException()" classname="main.UserExistsExceptionTest" time="0.004"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
